// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnpaYRtcz7zobom77EnsO2ZfhgBueTErs',
    appId: '1:444760830252:web:c5c055e0f5f114776ebc89',
    messagingSenderId: '444760830252',
    projectId: 'may-fair-17051',
    authDomain: 'may-fair-17051.firebaseapp.com',
    storageBucket: 'may-fair-17051.appspot.com',
    measurementId: 'G-ERJCJJWVC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTcGdoqI_AJM_UYosg0d1LF2AbM6gGL9w',
    appId: '1:444760830252:android:d7b0fc2d30e741c86ebc89',
    messagingSenderId: '444760830252',
    projectId: 'may-fair-17051',
    storageBucket: 'may-fair-17051.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Ez8WYMHH_N6Be3ZyFrHnZZ8UQgVYph8',
    appId: '1:444760830252:ios:1310d360c98d573e6ebc89',
    messagingSenderId: '444760830252',
    projectId: 'may-fair-17051',
    storageBucket: 'may-fair-17051.appspot.com',
    iosBundleId: 'com.example.mayFair',
  );
}
